Algoritmo "Dobro"

//solicitar 2 números para o usuário e mostrar a soma entre eles

Var
// Seção de Declarações das variáveis 
    n1, Dobra: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   EscrevaL ("Digite o número a ser Dobrado: ")
   
   Leia (n1)
   
   EscrevaL ("O número digitado Foi: ", n1)
   
     dobra <- n1 ^ 2

   EscrevaL ("O número dobrado é, ", dobra)



















Fimalgoritmo

